### ISSUE TITLE
New thread didn't display

### ISSUE THREAD

**Issue by IpsmLorem** [PeerioTechnologies/peerio-client#125] opened 2015-02-03 20:01 UTC
I just received an email notification for a new incoming message.
I launched peerio and the Message tab displayed, on a green, box a "1" meaning a new message. But no actual message was displayed
I relaunched peerio and finaly the new thread (first message of a new thread) was displayed and the green box disapeared.

**Comment by flohdot** [comment] 2015-02-03 20:04
Question: were you prompted for 2fa when logging back in?

**Comment by IpsmLorem** [comment] 2015-02-03 20:29
No it didn't asked me for (yes I have 2FA turned on). Further more, now I think about it, Peerio didn't asked for 2FA for a long time now.

**Comment by skylarnagao** [comment] 2015-03-27 23:23
@IpsmLorem Do you still experience this with the 1.0.4.2 release?

**Comment by IpsmLorem** [comment] 2015-03-28 11:22
Seems better so far.

**Comment by skylarnagao** [comment] 2015-03-30 20:38
Marking as cannot reproduce. Presumed to be fixed.

**Closed by skylarnagao** 2015-03-30 20:38 UTC
Labels: bug, cannot reproduce
