### ISSUE TITLE
Contact accepted notification

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#76] opened 2015-01-22 21:10 UTC
Add notification for when someone approves your contact request. Once you have more contacts than fit in the display, it becomes cumbersome to check in to see if that contact has approved you.

**Comment by hdf** [comment] 2015-01-25 12:02
Approvement indicator on the contact, and filtering/ordering option for approvement status?

**Comment by flohdot** [comment] 2015-01-26 23:00
By notification, do you mean email notification, desktop notification, sound, all of the above?

**Comment by skylarnagao** [comment] 2015-01-27 01:28
At least email and desktop. Sound doesn't hurt.

**Comment by kaepora** [comment] 2015-02-07 15:32
We don't have notification sounds designed for contact requests. Perhaps @zarag0ziegor can look into this.

**Comment by kaepora** [comment] 2015-02-07 15:35
I'm re-assigning this to @flohdot because:

1. The client currently has no way of telling which contact approved a request -- it just receives a `contactsAvailable` message from the server and updates the contact list.
2. If we want email notifications, Floh will have to implement those.

**Comment by flohdot** [comment] 2015-02-09 21:30
Reassigning to @kaepora. The client will need to diff a new contact list with an old to signal new contacts and or use the `isNew` flag that the server provides. Email notifications will be dealt with separately in #138

**Comment by kaepora** [comment] 2015-02-21 11:10
@flohdot Server issue: When I accept a contact and then do `getContacts` for the first time, I do not see them marked as new.

**Comment by flohdot** [comment] 2015-02-23 15:20
Do you mean you don't see them marked as new _only the first time_ you fetch the contact list after accepting? That is to say, if you wait a bit and fetch again they are marked as new?

**Comment by flohdot** [comment] 2015-02-23 18:02
Oh, actually, I just understood the issue. This is by design. If you accept a contact yourself it is not useful for it to be marked as new _for you_ -- in fact, that's kind of annoying to be alerted of something you yourself did. The contact relationship is marked as new for the person who sent the request, who should then be notified.

**Comment by flohdot** [comment] 2015-02-24 00:31
@kaepora `isNew` should work now. I'm getting notifications in the client when my requests are accepted so A+.

**Comment by skylarnagao** [comment] 2015-02-24 15:41
When logging in with the most recent updates pushed, accounts will receive desktop notifications for all their existing contacts when logging in for the first time since updating. e.g. "You are now contacts with _____!" for all your previous contacts. 

If you have 50 contacts, this leads to 50 desktop notifications sequentially.

**Closed** 2015-02-24 20:42 UTC
Labels: enhancement
