### ISSUE TITLE
Let user select message recipient with cursor keys

### ISSUE THREAD

**Issue by nilsws** [PeerioTechnologies/peerio-client#217] opened 2015-03-28 08:32 UTC
Currently, when composing a new message, the recipient must be selected from the drop down menu via mouse. Navigation keys don't work. Would be great to be able to create a new message without using the mouse.

**Comment by skylarnagao** [comment] 2015-03-30 18:09
Duplicate of #112

**Closed by skylarnagao** 2015-03-30 18:09 UTC
Labels: duplicate
