### ISSUE TITLE
Do not send email/SMS notifications if user is online/reads

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#60] opened 2015-01-20 23:51 UTC
If user is using Peerio and reads/acknowledges messages, say within a few minutes of receipt, do not send email/SMS notifications.

**Comment by mrbiber** [comment] 2015-01-22 11:52
+1 for delaying messages by about a minute and sending them only if there is no client interaction in between.

**Comment by Tiago235** [comment] 2015-01-22 16:26
+1!

**Comment by IpsmLorem** [comment] 2015-01-23 11:45
Closely related to #5

**Comment by kaepora** [comment] 2015-01-25 11:22
Duplicate of #5, actually.

**Closed by kaepora** 2015-01-25 11:22 UTC
Labels: duplicate
